name: libmtp
on: [push,pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configure_flags: [--disable-silent-rules, --with-udev-group=nobody --with-udev-mode=760, --disable-mtpz]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Create configure
        run: |
          sudo apt-get update -y
          sudo apt-get install autoconf automake libtool gcc libgcrypt-dev libusb-dev libusb-1.0-0-dev
          bash autogen.sh
      - name: Choose configure option(s)
        run: ./configure ${{ matrix.configure_flags }}
      - name: Make libmtp library
        run: make
      - name: Test make distcheck
        if: matrix.configure_flags == '--disable-silent-rules'
        run: make distcheck
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        configure_flags: [--disable-silent-rules, --disable-mtpz]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install dependencies
        run: brew install autoconf automake libtool gettext libgcrypt libusb
      - name: Create configure
        run: NOCONFIGURE=1 bash autogen.sh
      - name: Choose configure option(s)
        run: |
          PKG_CONFIG_PATH="$(brew --prefix libusb)/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}" \
            ./configure ${{ matrix.configure_flags }}
      - name: Make libmtp library
        run: make
